---
  AWSTemplateFormatVersion: '2010-09-09'
  Description: Sample template
  Resources:
    SampleVolume:
      Type: AWS::EC2::Volume
      Properties:
        Encrypted: true
        Size: 10
        VolumeType: gp2
        AvailabilityZone: us-west-2b