---
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample template
Resources:
  MyGp2Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-west-2b
      Encrypted: true
      Size: 10
      VolumeType: gp2
  MyIo1Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: us-west-2b
      Encrypted: true
      Iops: 1000
      Size: 30
      VolumeType: io1